### ISSUE TITLE
I see this problem

### ISSUE THREAD

**Issue by BaraaDev** [rakibdevs/openweather-laravel-api#1]
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Root composer.json requires rakibdevs/openweather-laravel-api ^1.0 -> satisfiable by rakibdevs/openweather-laravel-api[v1.0].
    - rakibdevs/openweather-laravel-api v1.0 requires guzzlehttp/guzzle ^7 -> found guzzlehttp/guzzle[dev-master, 7.0.0-beta.1, ..., 7.2.0] but it conflicts with your root composer.json require (^6.3).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by rakibdevs** [comment]
Thank you for noticing. I have updated composer.json .
