### ISSUE TITLE
WeatherException.php does not comply with psr-4 autoloading standard

### ISSUE THREAD

**Issue by jeffreyvanhees** [rakibdevs/openweather-laravel-api#2]
Hi,

Great package, thanks!

When installing this package by composer, I got the error 
```Class RakibDevs\Weather\Src\Exceptions\WeatherException located in ./vendor/rakibdevs/openweather-laravel-api/src/Exceptions/WeatherException.php does not comply with psr-4 autoloading standard. Skipping.```

It looks like it is because of the wrong namespace:
```RakibDevs\Weather\Src\Exceptions;```

**Comment by rakibdevs** [comment]
Thank you very much. It was the wrong namespace.
