### ISSUE TITLE
Wrong cities

### ISSUE THREAD

**Issue by Kazan1520** [rakibdevs/openweather-laravel-api#3]
After I try to get a weather of an not existing city, a page with json "cod" : "404" etc. is forced and i can't change it. Is there a way to work around it?

**Comment by rakibdevs** [comment]
If you try a non-existing city the weather data will result in 404. Please try with a valid city as Open Weather provides data only for a valid one.

**Comment by Kazan1520** [comment]
Yep. Version 1.5 looks nice. Thanks that you updated weather exception.
But still i guess it would be better if you just returned a json with error code and message.

**Comment by rakibdevs** [comment]
Thank you. I will try in next version.
