### ISSUE TITLE
 I got error message when a ran compose update 

### ISSUE THREAD

**Issue by magnokf** [rakibdevs/openweather-laravel-api#5]
Hi ! I got error message when a ran compose update (laravel 7)
ErrorException

  Undefined property: stdClass::$date_format

  at G:\server\htdocs\my-project\vendor\rakibdevs\openweather-laravel-api\src\Weather.php:110

I couldnt find any fixes, maybe you already have a solution?? Thanks in advance

**Comment by rakibdevs** [comment]
Did you publish the `config` file. This is more likely 
```php
return [
    'api_key'  => '',
    'lang' => 'en',
    'date_format' => 'm/d/Y',
    'time_format' => 'h:i A',
    'day_format' => 'l',
    'temp_format' => 'c'         // c for celcius, f for farenheit, k for kelvin
];
```
