### ISSUE TITLE
error to install

### ISSUE THREAD

**Issue by EduardEddy** [rakibdevs/openweather-laravel-api#6]
i try to install i run only  composer require rakibdevs/openweather-laravel-api
and recive this message
  There was no `api_key` specified. You must provide a valid API KEY to get weather data from Open Weather.

**Comment by rakibdevs** [comment]
Please get the API key from https://openweathermap.org/api and add in configuration.

**Comment by taraqr9** [comment]
How can I add api_key in config file before installation?
