### ISSUE TITLE
Upgrade to 3.0 API

### ISSUE THREAD

**Issue by DanielMalmgren** [rakibdevs/openweather-laravel-api#8]
When I first tried I got "Invalid API key" and it seems my newly created account is only valid for the newer 3.0 API. After changing 2.5 to 3.0 in the $url in WeatherClient everything works fine. I guess maybe this should be a config option?

**Comment by rakibdevs** [comment]
Thank you for the suggestion. I will work on it. Only the One Call API is updated https://openweathermap.org/api/one-call-3

**Comment by rakibdevs** [comment]
Hi @DanielMalmgren , I have released v1.8.0 with version compatibility. Please update package.
